version: '3'

services:

  tpe:
    container_name: tpe
    build:
      context: ./tpe
    volumes:
      - ./apks:/tpe/apk

  shop:
    container_name: shop
    build:
      context: ./shop
    volumes:
      - ./apks:/shop/apk

  api:
    container_name: api
    build: 
      context: ./api
      dockerfile: Dockerfile.prod
    restart: unless-stopped
    environment:
      DB_NAME: ${DB_NAME}
      DB_PORT: ${DB_PORT}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_HOST: ${DB_HOST}
      HIBERNATE_DDL_AUTO: ${HIBERNATE_DDL_AUTO}
      HIBERNATE_SHOW_SQL: ${HIBERNATE_SHOW_SQL}
      DEVTOOLS_REMOTE_SECRET: ${DEVTOOLS_REMOTE_SECRET}
      DEVTOOLS_LIVERELOAD_ENABLED: ${DEVTOOLS_LIVERELOAD_ENABLED}
      REDIS_HOST: ${REDIS_HOST}
      REDIS_PORT: ${REDIS_PORT}
      JWT_SECRET: ${JWT_SECRET}
    volumes:
      - ./apks:/apks
    ports:
      - ${API_PORT}:${API_PORT}
    networks:
      - back-net
    depends_on:
      - database
      - shop
      - tpe

  redis:
    container_name: redis
    image: redis:alpine
    restart: unless-stopped
    command: redis-server --save 20 1 --requirepass ${REDIS_PASSWORD}
    ports:
      - ${REDIS_PORT}:${REDIS_PORT}
    volumes:
      - ./redis-data:/data
    networks:
      - back-net

  database:
    container_name: database
    image: mariadb:latest
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MARIADB_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
    ports:
      - ${DB_PORT}:${DB_PORT}
    volumes:
      - ./database-data:/var/lib/mysql
    networks:
      - back-net
  
volumes:
  database-data:
  redis-data:
  apks:
  
networks:
  back-net: