version: '3'

services:

  api:
    container_name: api
    build: 
      context: ./api
    restart: unless-stopped
    env_file:
      - ./env/database.env
      - ./env/redis.env
      - ./env/api.env
      - ./env/tpe.env
      - ./env/shop.env
    ports:
      - ${API_PORT}:${API_PORT}
    volumes:
      - ./api:/api
      - ./apks:/apks
    networks:
      - back-net
    depends_on:
      - database
      - redis

  redis:
    container_name: redis
    image: redis:alpine
    restart: unless-stopped
    command: redis-server --save 20 1 --requirepass ${REDIS_PASSWORD}
    ports:
      - ${REDIS_PORT}:${REDIS_PORT}
    volumes:
      - ./redis-data:/data
    networks:
      - back-net

  database:
    container_name: database
    image: mariadb:latest
    restart: unless-stopped
    env_file:
      - ./env/database.env
    ports:
      - ${MARIADB_PORT}:${MARIADB_PORT}
    volumes:
      - ./database-data:/var/lib/mysql
    networks:
      - back-net
    
volumes:
  database-data:
  redis-data:
  api:
  apks:

networks:
  back-net: