version: '3'

services:

  api:
    container_name: api
    build: 
      context: ./api
    restart: unless-stopped
    environment:
      DB_NAME: ${DB_NAME}
      DB_PORT: ${DB_PORT}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_HOST: ${DB_HOST}
      HIBERNATE_DDL_AUTO: ${HIBERNATE_DDL_AUTO}
      HIBERNATE_SHOW_SQL: ${HIBERNATE_SHOW_SQL}
      DEVTOOLS_REMOTE_SECRET: ${DEVTOOLS_REMOTE_SECRET}
      DEVTOOLS_LIVERELOAD_ENABLED: ${DEVTOOLS_LIVERELOAD_ENABLED}
      REDIS_HOST: ${REDIS_HOST}
      REDIS_PORT: ${REDIS_PORT}
      REDIS_PASSWORD: ${REDIS_PASSWORD}
      JWT_SECRET: ${JWT_SECRET}
      DEFAULT_MANAGER_USERNAME: ${DEFAULT_MANAGER_USERNAME}
      DEFAULT_MANAGER_PASSWORD: ${DEFAULT_MANAGER_PASSWORD}
    ports:
      - ${API_PORT}:${API_PORT}
    volumes:
      - ./api:/api
      - ./apks:/apks
    networks:
      - back-net
    depends_on:
      - database
      - redis

  redis:
    container_name: redis
    image: redis:alpine
    restart: unless-stopped
    command: redis-server --save 20 1 --requirepass ${REDIS_PASSWORD}
    ports:
      - ${REDIS_PORT}:${REDIS_PORT}
    volumes:
      - ./redis-data:/data
    networks:
      - back-net

  database:
    container_name: database
    image: mariadb:latest
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MARIADB_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
    ports:
      - ${DB_PORT}:${DB_PORT}
    volumes:
      - ./database-data:/var/lib/mysql
    networks:
      - back-net
    
volumes:
  database-data:
  redis-data:
  api:
  apks:

networks:
  back-net: