version: '3'

services:

  # tpe:
  #   container_name: tpe
  #   build:
  #     context: ./tpe
  #   volumes:
  #     - ./apks:/tpe/apk
  #   env_file:
  #     - ./env/prod/tpe.env

  # shop:
  #   container_name: shop
  #   build:
  #     context: ./shop
  #   volumes:
  #     - ./apks:/shop/apk
  #   env_file:
  #     - ./env/prod/shop.env

  api:
    container_name: api
    build: 
      context: ./api
      dockerfile: Dockerfile.prod
      args:
        API_PORT: ${API_PORT}
    restart: unless-stopped
    env_file:
      - ./env/prod/database.env
      - ./env/prod/redis.env
      - ./env/prod/api.env
      - ./env/prod/tpe.env
      - ./env/prod/shop.env
    volumes:
      - ./apks:/apks
    ports:
      - 80:${API_PORT}
    networks:
      - back-net
    depends_on:
      - database
      # - shop
      # - tpe

  redis:
    container_name: redis
    image: redis:alpine
    restart: unless-stopped
    command: redis-server --save 20 1 --requirepass ${REDIS_PASSWORD}
    volumes:
      - ./redis-data:/data
    expose:
      - "${REDIS_PORT}"
    networks:
      - back-net

  database:
    container_name: database
    image: mariadb:latest
    restart: unless-stopped
    env_file:
      - ./env/prod/database.env
    volumes:
      - ./database-data:/var/lib/mysql
    expose:
      - "${MARIADB_PORT}"
    networks:
      - back-net
  
volumes:
  database-data:
  redis-data:
  apks:
  
networks:
  back-net: