version: '3'

services:

  nginx:
    image: jwilder/nginx-proxy
    container_name: nginx
    ports:
      - "443:443"
      - "80:80"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - letsencrypt-certs:/etc/nginx/certs
      - letsencrypt-vhost-d:/etc/nginx/vhost.d
      - letsencrypt-html:/usr/share/nginx/html

  letsencrypt:
    image: jrcs/letsencrypt-nginx-proxy-companion
    container_name: letsencrypt
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - letsencrypt-certs:/etc/nginx/certs
      - letsencrypt-vhost-d:/etc/nginx/vhost.d
      - letsencrypt-html:/usr/share/nginx/html
    environment:
      - DEFAULT_EMAIL=cash-manager@gmail.com
      - NGINX_PROXY_CONTAINER=nginx

networks: 
  default: 
    external: 
      name: proxy-net

volumes:
  letsencrypt-certs:
  letsencrypt-vhost-d:
  letsencrypt-html: