version: '3'

services:
  api:
    container_name: api
    image: eliottclavier/cashmanager-api:latest
    # build: 
    #   context: ./api
    #   dockerfile: Dockerfile.prod
    #   args:
    #     API_PORT: ${API_PORT}
    restart: unless-stopped
    env_file:
      - ./env/database.env
      - ./env/redis.env
      - ./env/api.env
      - ./env/tpe.env
      - ./env/shop.env
    volumes:
      - ./apks:/apks
    expose:
      - "${API_PORT}"
    networks:
      - back-net
      - nginx-proxy
    depends_on:
      - database

  redis:
    container_name: redis
    image: redis:alpine
    restart: unless-stopped
    command: redis-server --save 20 1 --requirepass ${REDIS_PASSWORD}
    volumes:
      - ./redis-data:/data
    expose:
      - "${REDIS_PORT}"
    networks:
      - back-net

  database:
    container_name: database
    image: mariadb:latest
    restart: unless-stopped
    env_file:
      - ./env/database.env
    volumes:
      - ./database-data:/var/lib/mysql
    expose:
      - "${MARIADB_PORT}"
    networks:
        - back-net
  
volumes:
  database-data:
  redis-data:
  apks:
  
networks:
  back-net:
  nginx-proxy:
    external:
      name: nginx-proxy
