package com.api.gateway.transaction.model;

public enum MessageType {
    PENDING,
    TRANSACTION_OPENED,
    TRANSACTION_DONE,
    TRANSACTION_INVALID,
    TRANSACTION_CANCELLED,
    TRANSACTION_ERROR,
    SYNCHRONIZED,
    SYNCHRONIZATION_ERROR,
    ALREADY_SYNCHRONIZED,
    TPE_INVALID,
    NOT_INVOLVED,
    NOT_FOUND,
    NO_TPE_FOUND,
    NO_TPE_SELECTED,
    INVALID_PAYMENT_METHOD,
    STILL_AVAILABLE,
    LOST_CONNECTION,
    ALREADY_IN_TRANSACTION
}
