package com.api.bank.model.enums;

public enum TransactionStatus {
    SUCCESS,
    FAILED,
    PAYMENT_ERROR,
    MEANS_OF_PAYMENT_ERROR,
    CARD_ERROR,
    VALIDITY_DATE_ERROR,
    CHECK_ERROR,
    TOKEN_EMPTY_ERROR,
    TOKEN_ERROR,
    BANK_ERROR,
    INSUFFICIENT_FUNDS_ERROR,
    OPERATION_PENDING_ERROR,
    OPERATION_CLOSING_ERROR,
    ACCOUNT_ERROR,
    EMPTY_TRANSACTION_ERROR,
}
