name: Build and publish Shop APK

on:
  push:
    branches:
      - main
      - develop
      - feature/variabilize

jobs:
  build_from_build_workflow:
    uses: ./.github/workflows/build-apks.yml
    with:
      app_dir: shop
      apk_name: shop.apk
      dart_defines: |
        API_URL=API_URL;
        SHOP_USERNAME=SHOP_USERNAME;
        SHOP_PASSWORD=SHOP_PASSWORD;