name: Build and publish TPE APK

on: [workflow_call]

jobs:
  build_from_build_workflow:
    name: Build and publish TPE APK 
    uses: ./.github/workflows/build-apks.yml
    with:
      app_dir: tpe
      apk_name: tpe.apk
      dart_defines: |
        API_URL=API_URL;
        TPE_REGISTER_SECRET_HEADER=TPE_REGISTER_SECRET_HEADER;
        TPE_REGISTER_SECRET_KEY=TPE_REGISTER_SECRET_KEY;