name: Build and publish APKs

on:
  workflow_call:

jobs:
  build_apk:
    name: Build APK    
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
      
      - name: Get dependencies
        run: flutter pub get
        working-directory: ./shop
      
      - name: Build APK
        run: flutter build apk --release 
          --dart-define=API_URL=\'${{ secrets.API_URL }}\' 
          --dart-define=SHOP_USERNAME=\'${{ secrets.SHOP_USERNAME }}\'
          --dart-define=SHOP_PASSWORD=\'${{ secrets.SHOP_PASSWORD }}\'
        working-directory: ./shop
      
      - name: Create .tar artifact
        run: mv app-release.apk shop.apk && tar -cvf shop.tar shop.apk
        working-directory: ./shop/build/app/outputs/flutter-apk/

      - name: Upload .tar APK artifact
        uses: actions/upload-artifact@v2
        with:
          name: shop.tar
          artifact_format: tar
          path: ./shop/build/app/outputs/flutter-apk/shop.tar
