name: Build and publish TPE .apk

on:
  push:
    branches:
      - main
      - develop
      - feature/variabilize

jobs: 
  build_tpe_apk:
    runs-on:
      ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Flutter
      uses: subosito/flutter-action@v2

    - name: Build APK
      run: cd ./tpe && flutter clean && flutter pub get && flutter build apk --release

    - name: Upload APK artifact
      uses: actions/upload-artifact@v2
      with:
        name: tpe.apk
        path: build/app/outputs/apk/release/app-release.apk