name: Build and publish TPE APK

on:
  push:
    branches:
      - main
      - develop
      - feature/variabilize

jobs:
  build_from_build_workflow:
    uses: ./.github/workflows/build-apks.yml
    with:
      app_dir: tpe
      apk_name: tpe.apk
      dart_defines: |
        API_URL=API_URL;
        TPE_REGISTER_SECRET_HEADER=TPE_REGISTER_SECRET_HEADER;
        TPE_REGISTER_SECRET_KEY=TPE_REGISTER_SECRET_KEY;