name: Deploy

on:
  push:
    branches:
      - feature/variabilize

jobs:
  build_tpe_apk:
    name: Build and publish TPE APK 
    uses: ./.github/workflows/build-apks.yml
    with:
      app_dir: tpe
      apk_name: tpe.apk
      dart_defines: |
        API_URL=API_URL;
        TPE_REGISTER_SECRET_HEADER=TPE_REGISTER_SECRET_HEADER;
        TPE_REGISTER_SECRET_KEY=TPE_REGISTER_SECRET_KEY;

  build_shop_apk:
    name: Build and publish Shop APK 
    uses: ./.github/workflows/build-apks.yml
    with:
      app_dir: shop
      apk_name: shop.apk
      dart_defines: |
        API_URL=API_URL;
        SHOP_USERNAME=SHOP_USERNAME;
        SHOP_PASSWORD=SHOP_PASSWORD;