name: Deploy on remote server

on:
  workflow_call:

jobs:
  deploy:
    name: Deploy on remote server
    runs-on: ubuntu-latest
    steps:
      - name: Execute script to setup docker-compose architecture
        run: |
          ssh -i "${{ secrets.SERVER_SSH_KEY }}" ${{ secrets.SERVER_USERNAME }}@${{ secrets.SERVER_IP }} \
          'cd /app/ && sh ./deploy.sh'